//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMeetingRoom.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BookingTab
    {
        public int BookingId { get; set; }
        [Display(Name = "Room")]
        [Required(ErrorMessage = "Please enter Meeting Room.")]
        public string RoomNo { get; set; }
        [Display(Name = "Meeting Date")]
        [Required(ErrorMessage = "Please select Meeting Date.")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> MeetingDt { get; set; }
        [Display(Name = "Start Time")]
        [Required(ErrorMessage = "Please enter Meeting Start Time.")]
        [DataType(DataType.Time)]
        public Nullable<System.TimeSpan> StartTime { get; set; }
        [Display(Name = "End Time")]
        [Required(ErrorMessage = "Please enter Meeting End Time.")]
        [DataType(DataType.Time)]
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public string Subject { get; set; }
        public string ErrorMessage { get; set; }


        public virtual RoomTab RoomTab { get; set; }
    }
}
