//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMeetingRoom.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RoomTab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomTab()
        {
            this.BookingTabs = new HashSet<BookingTab>();
        }
        [Display(Name = "Room No.")]
        [Required(ErrorMessage = "Please enter Room No.")]
        public string RoomNo { get; set; }
        [Display(Name = "Room Name")]
        [Required(ErrorMessage = "Please enter Room Name.")]
        public string RoomName { get; set; }
        [Display(Name = "Room Level")]
        public string RoomLevel { get; set; }
        public string ErrorMessage { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingTab> BookingTabs { get; set; }
    }
}
